package document_generation.StatementOfClaim.Sections.Codes;

public enum SOCSectionCode { START, START2, PARTIES, BACKGROUND, INDEPENDENT, TERMINATION, CONSTRUCTIVE, WAGE,
	LOCATION, INTOLERABLE, WORKPLACE_HARASSMENT, POISONED, REMOVAL_MANAGEMENT, FIGHTING_CAUSE,
	HIGH_STANDARD, GROSS, ABANDONMENT, DAMAGE_AWARD, FIGHTING_TERM, NO_CONTRACTING,
	NOT_EXCLUDE, NON_BENEFITS, POT_VIOLATIONS, ABoCDSR, INDUCEMENT, WRONGFUL, CLC,
	ONT_OVERTIME, BONUSES_OTHERS, OHSA, PUNITIVE_HARASSMENT, HUMAN_RIGHTS, PUN_AGG_MOR_DMGS, 
	BAD_FAITH, OPEN_HONEST, ALLEGATIONS, HARASSMENT, FAIL_MINIMUMS, END_LOCATION, END,
	CUSTOM, START_TEST, NUM
 }
//pension not in SOC
//no 'appropriate notice period' in SOC
//punitive damages == punitive harassment?