package document_generation.LawyersLetter.Codes;

/**
 * Created by Yale Wang
 */
public enum SectionCode { IMG, OPENING, ADDRESSEE, RE, EMP_DESC, TERMINATION, CONSTRUCTIVE_DISMISSAL, BONUS, FIGHT_TERMINATION_CLAUSE, FIGHTING_CAUSE, CONTRACTOR_VS_EMP, PENSION, APPROPRIATE_NOTICE_PERIOD, INDUCEMENT, HARASSMENT, HUMAN_RIGHTS_DIS, PUNITIVE_DMGS, OVERTIME, MOVING_FWD, LTD_JURISPRUDENCE, CLOSE, CUSTOM }
